Update Part 3 - Training Neural Networks (Exercises).ipynb
when torchvision is updated to 0.2.2, need change parameters of transforms.Normalize from (0.5, 0.5, 0.5) to (0.5, ), otherwise will get error below when iterate through trainloader:

~\Anaconda3\lib\site-packages\torchvision\transforms\functional.py in normalize(tensor, mean, std, inplace)
    206     mean = torch.tensor(mean, dtype=torch.float32)
    207     std = torch.tensor(std, dtype=torch.float32)
--> 208     tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
    209     return tensor
    210 

RuntimeError: output with shape [1, 28, 28] doesn't match the broadcast shape [3, 28, 28]